version: "3.2"

services:
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbit'
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=senhadev
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net

volumes:
    rabbitmq_data:
    rabbitmq_log:

networks:
  rabbitmq_go_net:
    driver: bridge